using Celarix.Starfall.Rendering.Models;
using OpenTK.Windowing.GraphicsLibraryFramework;
using System;
using System.Collections.Generic;
using System.Text;

namespace Celarix.Starfall.Extensions
{
    public static class SKeyExtensions
    {
        public static SKey ToSKey(this Keys keys)
        {
            return keys switch
            {
                Keys.Unknown => SKey.Unknown,
                Keys.Space => SKey.Space,
                Keys.Apostrophe => SKey.Apostrophe,
                Keys.Comma => SKey.Comma,
                Keys.Minus => SKey.Minus,
                Keys.Period => SKey.Period,
                Keys.Slash => SKey.Slash,
                Keys.D0 => SKey.D0,
                Keys.D1 => SKey.D1,
                Keys.D2 => SKey.D2,
                Keys.D3 => SKey.D3,
                Keys.D4 => SKey.D4,
                Keys.D5 => SKey.D5,
                Keys.D6 => SKey.D6,
                Keys.D7 => SKey.D7,
                Keys.D8 => SKey.D8,
                Keys.D9 => SKey.D9,
                Keys.Semicolon => SKey.Semicolon,
                Keys.Equal => SKey.Equal,
                Keys.A => SKey.A,
                Keys.B => SKey.B,
                Keys.C => SKey.C,
                Keys.D => SKey.D,
                Keys.E => SKey.E,
                Keys.F => SKey.F,
                Keys.G => SKey.G,
                Keys.H => SKey.H,
                Keys.I => SKey.I,
                Keys.J => SKey.J,
                Keys.K => SKey.K,
                Keys.L => SKey.L,
                Keys.M => SKey.M,
                Keys.N => SKey.N,
                Keys.O => SKey.O,
                Keys.P => SKey.P,
                Keys.Q => SKey.Q,
                Keys.R => SKey.R,
                Keys.S => SKey.S,
                Keys.T => SKey.T,
                Keys.U => SKey.U,
                Keys.V => SKey.V,
                Keys.W => SKey.W,
                Keys.X => SKey.X,
                Keys.Y => SKey.Y,
                Keys.Z => SKey.Z,
                Keys.LeftBracket => SKey.LeftBracket,
                Keys.Backslash => SKey.Backslash,
                Keys.RightBracket => SKey.RightBracket,
                Keys.GraveAccent => SKey.GraveAccent,
                Keys.Escape => SKey.Escape,
                Keys.Enter => SKey.Enter,
                Keys.Tab => SKey.Tab,
                Keys.Backspace => SKey.Backspace,
                Keys.Insert => SKey.Insert,
                Keys.Delete => SKey.Delete,
                Keys.Right => SKey.Right,
                Keys.Left => SKey.Left,
                Keys.Down => SKey.Down,
                Keys.Up => SKey.Up,
                Keys.PageUp => SKey.PageUp,
                Keys.PageDown => SKey.PageDown,
                Keys.Home => SKey.Home,
                Keys.End => SKey.End,
                Keys.CapsLock => SKey.CapsLock,
                Keys.ScrollLock => SKey.ScrollLock,
                Keys.NumLock => SKey.NumLock,
                Keys.PrintScreen => SKey.PrintScreen,
                Keys.Pause => SKey.Pause,
                Keys.F1 => SKey.F1,
                Keys.F2 => SKey.F2,
                Keys.F3 => SKey.F3,
                Keys.F4 => SKey.F4,
                Keys.F5 => SKey.F5,
                Keys.F6 => SKey.F6,
                Keys.F7 => SKey.F7,
                Keys.F8 => SKey.F8,
                Keys.F9 => SKey.F9,
                Keys.F10 => SKey.F10,
                Keys.F11 => SKey.F11,
                Keys.F12 => SKey.F12,
                Keys.F13 => SKey.F13,
                Keys.F14 => SKey.F14,
                Keys.F15 => SKey.F15,
                Keys.F16 => SKey.F16,
                Keys.F17 => SKey.F17,
                Keys.F18 => SKey.F18,
                Keys.F19 => SKey.F19,
                Keys.F20 => SKey.F20,
                Keys.F21 => SKey.F21,
                Keys.F22 => SKey.F22,
                Keys.F23 => SKey.F23,
                Keys.F24 => SKey.F24,
                Keys.F25 => SKey.F25,
                Keys.KeyPad0 => SKey.KeyPad0,
                Keys.KeyPad1 => SKey.KeyPad1,
                Keys.KeyPad2 => SKey.KeyPad2,
                Keys.KeyPad3 => SKey.KeyPad3,
                Keys.KeyPad4 => SKey.KeyPad4,
                Keys.KeyPad5 => SKey.KeyPad5,
                Keys.KeyPad6 => SKey.KeyPad6,
                Keys.KeyPad7 => SKey.KeyPad7,
                Keys.KeyPad8 => SKey.KeyPad8,
                Keys.KeyPad9 => SKey.KeyPad9,
                Keys.KeyPadDecimal => SKey.KeyPadDecimal,
                Keys.KeyPadDivide => SKey.KeyPadDivide,
                Keys.KeyPadMultiply => SKey.KeyPadMultiply,
                Keys.KeyPadSubtract => SKey.KeyPadSubtract,
                Keys.KeyPadAdd => SKey.KeyPadAdd,
                Keys.KeyPadEnter => SKey.KeyPadEnter,
                Keys.KeyPadEqual => SKey.KeyPadEqual,
                Keys.LeftShift => SKey.LeftShift,
                Keys.LeftControl => SKey.LeftControl,
                Keys.LeftAlt => SKey.LeftAlt,
                Keys.LeftSuper => SKey.LeftSuper,
                Keys.RightShift => SKey.RightShift,
                Keys.RightControl => SKey.RightControl,
                Keys.RightAlt => SKey.RightAlt,
                Keys.RightSuper => SKey.RightSuper,
                Keys.Menu => SKey.Menu,
                _ => throw new ArgumentOutOfRangeException(nameof(keys), $"Unsupported key: {keys}")
            };
        }
    }
}
